Dir : 
  root : /home/username/Projects/ProjectName 
  data_path : G:\CamVid\dataset\DronData/
  original_data_path : G:\CamVid\dataset\DronData\dataset\semantic_drone_dataset\original_images/
  label_path : G:\CamVid\dataset\DronData\dataset\semantic_drone_dataset\label_images_semantic/
  model_dir : G:\CamVid\artifacts/model_ckpt/model_v1.pth

Callback_config: 

  aritifact_path : G:\CamVid\artifacts/
  model_ckpt : G:\CamVid\artifacts\model_ckpt/
  log_dir : C:\Users\Amzad\Desktop\camvid-segmentation\artifacts\logs/
  fig : G:\CamVid\fig/

Train_config : 
  num_classes : 22
  batch_size : 8
  epochs : 10
  learning_rate : 0.0001
  momentum : 0.9
  weight_decay : 0.0005
  num_workers : 0
  print_freq : 10
  save_freq : 10
  device : cuda
  seed : 42
  

Model_config : 

  model_name : Unet
  num_classes : 22


Transform_config: 
  
  image_size : 512
  horizontal_flip_prob : 0.5
  vertical_flip_prob : 0.5 
  blur_prob : 0.1 
  blur_limit : 0.3
  rotate : 0.1
  scale_limit : 0.2
  rotate_limit : 20
  shift_limit : 0.1
  p : 0.5
  border_mode : 0

Data_injection :
  train_split : 0.8
  val_split : 0.1
  test_split : 0.1
  train_csv : G:\CamVid\artifacts\train.csv
  val_csv : G:\CamVid\artifacts\val.csv
  test_csv : G:\CamVid\artifacts\test.csv






  